version: '2'

services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app